spring:
  application:
    name: wallet-ledger-system
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_ledger
    username: wallet
    password: wallet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
